name: 'crossbring_dbt'
version: '1.0.0'
config-version: 2

profile: 'crossbring'

model-paths: ['models']
seed-paths: ['seeds']
test-paths: ['tests']
macro-paths: ['macros']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  crossbring_dbt:
    +materialized: view
    staging:
      +schema: staging
      +materialized: table
    marts:
      +schema: marts
      +materialized: table

