name: Crossbring dbt CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-warehouse-dbt
    env:
      HAS_SNOWFLAKE: ${{ secrets.SNOWFLAKE_ACCOUNT != '' && secrets.SNOWFLAKE_USER != '' && secrets.SNOWFLAKE_PASSWORD != '' && secrets.SNOWFLAKE_ROLE != '' && secrets.SNOWFLAKE_WAREHOUSE != '' && secrets.SNOWFLAKE_DATABASE != '' && secrets.SNOWFLAKE_SCHEMA != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake
      - name: Configure dbt profile
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          crossbring:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 4
                client_session_keep_alive: false
          YAML
      - run: dbt deps
      - name: dbt seed
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        run: dbt seed --full-refresh
      - name: dbt run
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        run: dbt run
      - name: dbt test
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        run: dbt test
      - name: dbt docs generate
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        run: dbt docs generate
      - name: dbt parse (no Snowflake secrets)
        if: ${{ env.HAS_SNOWFLAKE != 'true' }}
        run: dbt parse
      - uses: actions/upload-artifact@v4
        if: ${{ env.HAS_SNOWFLAKE == 'true' }}
        with:
          name: dbt-target
          path: 01-warehouse-dbt/target
      - uses: actions/upload-artifact@v4
        if: ${{ env.HAS_SNOWFLAKE != 'true' }}
        with:
          name: dbt-manifest
          path: 01-warehouse-dbt/target/manifest.json
