name: Crossbring dbt Docs Publish

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'crossbring-data-portfolio/01-warehouse-dbt/**'

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: crossbring-data-portfolio/01-warehouse-dbt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake
      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          crossbring:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 4
                client_session_keep_alive: false
          YAML
      - run: dbt deps
      - run: dbt seed --full-refresh
      - run: dbt run
      - run: dbt test
      - run: dbt docs generate
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: crossbring-data-portfolio/01-warehouse-dbt/target
          destination_dir: dbt-docs

