name: Crossbring dbt CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 01-warehouse-dbt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake
      - name: Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          crossbring:
            target: ci
            outputs:
              ci:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 4
                client_session_keep_alive: false
          YAML
      - run: dbt deps
      - run: dbt seed --full-refresh
      - run: dbt run
      - run: dbt test
      - run: dbt docs generate
      - uses: actions/upload-artifact@v4
        with:
          name: dbt-target
          path: 01-warehouse-dbt/target
